/* tslint:disable */
/* eslint-disable */
/**
 * Vueハンズオン
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type CoffeeHotGet200ResponseInnerId
 * 
 * @export
 */
export type CoffeeHotGet200ResponseInnerId = number | string;

export function CoffeeHotGet200ResponseInnerIdFromJSON(json: any): CoffeeHotGet200ResponseInnerId {
    return CoffeeHotGet200ResponseInnerIdFromJSONTyped(json, false);
}

export function CoffeeHotGet200ResponseInnerIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoffeeHotGet200ResponseInnerId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return json;
}

export function CoffeeHotGet200ResponseInnerIdToJSON(value?: CoffeeHotGet200ResponseInnerId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfnumber(value)) {
        return numberToJSON(value as number);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

