/* tslint:disable */
/* eslint-disable */
/**
 * Vueハンズオン
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoffeeIcedGet200ResponseInner
 */
export interface CoffeeIcedGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof CoffeeIcedGet200ResponseInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CoffeeIcedGet200ResponseInner
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CoffeeIcedGet200ResponseInner
     */
    ingredients?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CoffeeIcedGet200ResponseInner
     */
    image?: string;
    /**
     * 
     * @type {number}
     * @memberof CoffeeIcedGet200ResponseInner
     */
    id?: number;
}

/**
 * Check if a given object implements the CoffeeIcedGet200ResponseInner interface.
 */
export function instanceOfCoffeeIcedGet200ResponseInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CoffeeIcedGet200ResponseInnerFromJSON(json: any): CoffeeIcedGet200ResponseInner {
    return CoffeeIcedGet200ResponseInnerFromJSONTyped(json, false);
}

export function CoffeeIcedGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoffeeIcedGet200ResponseInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'ingredients': !exists(json, 'ingredients') ? undefined : json['ingredients'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function CoffeeIcedGet200ResponseInnerToJSON(value?: CoffeeIcedGet200ResponseInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'ingredients': value.ingredients,
        'image': value.image,
        'id': value.id,
    };
}

