/* tslint:disable */
/* eslint-disable */
/**
 * Vueハンズオン
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface CoffeeHotGet200ResponseInner
 */
export interface CoffeeHotGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof CoffeeHotGet200ResponseInner
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CoffeeHotGet200ResponseInner
     */
    'description'?: string;
    /**
     * 
     * @type {CoffeeHotGet200ResponseInnerIngredients}
     * @memberof CoffeeHotGet200ResponseInner
     */
    'ingredients'?: CoffeeHotGet200ResponseInnerIngredients;
    /**
     * 
     * @type {string}
     * @memberof CoffeeHotGet200ResponseInner
     */
    'image'?: string;
    /**
     * 
     * @type {CoffeeHotGet200ResponseInnerId}
     * @memberof CoffeeHotGet200ResponseInner
     */
    'id'?: CoffeeHotGet200ResponseInnerId;
}
/**
 * @type CoffeeHotGet200ResponseInnerId
 * @export
 */
export type CoffeeHotGet200ResponseInnerId = number | string;

/**
 * @type CoffeeHotGet200ResponseInnerIngredients
 * @export
 */
export type CoffeeHotGet200ResponseInnerIngredients = Array<string> | string;


/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coffeeHotGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/coffee/hot`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coffeeHotGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CoffeeHotGet200ResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coffeeHotGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coffeeHotGet(options?: any): AxiosPromise<Array<CoffeeHotGet200ResponseInner>> {
            return localVarFp.coffeeHotGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public coffeeHotGet(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).coffeeHotGet(options).then((request) => request(this.axios, this.basePath));
    }
}


