/* tslint:disable */
/* eslint-disable */
/**
 * Vueハンズオン
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CoffeeHotGet200ResponseInner,
  CoffeeIcedGet200ResponseInner,
} from '../models';
import {
    CoffeeHotGet200ResponseInnerFromJSON,
    CoffeeHotGet200ResponseInnerToJSON,
    CoffeeIcedGet200ResponseInnerFromJSON,
    CoffeeIcedGet200ResponseInnerToJSON,
} from '../models';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async coffeeHotGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CoffeeHotGet200ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/coffee/hot`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CoffeeHotGet200ResponseInnerFromJSON));
    }

    /**
     */
    async coffeeHotGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CoffeeHotGet200ResponseInner>> {
        const response = await this.coffeeHotGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async coffeeIcedGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CoffeeIcedGet200ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/coffee/iced`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CoffeeIcedGet200ResponseInnerFromJSON));
    }

    /**
     */
    async coffeeIcedGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CoffeeIcedGet200ResponseInner>> {
        const response = await this.coffeeIcedGetRaw(initOverrides);
        return await response.value();
    }

}
